import os

DROPBOX_CLIENT_ID = os.getenv("DROPBOX_CLIENT_ID", "")

DROPBOX_CLIENT_SECRET = os.getenv("DROPBOX_CLIENT_SECRET", "")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")

GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")

OAUTH_REDIRECT_URI = os.getenv("OAUTH_REDIRECT_URI", "http://localhost:3000/oauth/login_cb")

JWT_SIGNKEY = os.getenv("JWT_SIGNKEY", "44524889A72732256A9C92F1ADD1EF80F459431BA35FBCCB5D57CB03EF4C4FC8")



