.TH texmaker 1 "July 2, 2014"
.
.SH NAME
texmaker \(em A Cross-Platform LaTeX Editor
.
.SH SYNOPSIS
.SY texmaker
.OP -master
.OP -line xx
.OP \-\-
.
.\" Ellipsis
.ie t .char \(el \f[S]\N'188'\fP
.el .char \(el ...
.
.OP file \(el
.
.
.SH DESCRIPTION
.B texmaker
is a clean, highly configurable LaTeX editor with good hot key support
and extensive Latex documentation.
.
Texmaker integrates many tools needed to develop documents with LaTeX,
in just one application.
.
It has some nice featuressuch as syntax highlighting, insertion of 370
mathematical symbols with only one click, a structure view of the
document for easier navigation.
.
.TP
.B \-master
With this option, the document will be automatically defined as a
"master" document.
.
.TP
.BI \-line xx
With this option, Texmaker will ask you if you want to jump to the
.I xx
line after loading the document.
.
.P
See the user manuels under the 'Help' directory for documentation on
the use and features for Texmaker.
.
.
.SH FEATURES
Some of Texmaker's features are:
.
.\" A bulleted paragraph
.de Topic
.  .ds @i 2m\"
.  ie t .IP \[bu] \\*(@i
.  el .IP \-
.  rm @i
..
.
.Topic
An unicode editor to write your LaTeX source files (syntax
highlighting, undo-redo, search-replace, \(el)
.
.Topic
The principal LaTex tags can be inserted directly with the
.I LaTeX
and
.I Math
menus
.
.Topic
370 mathematical symbols can be inserted in just one click
.
.Topic
Wizards to generate code
.RB ( "Quick document" ,
.BR "Quick letter" ,
tabular, tabbing and array environments)
.
.Topic
LaTeX-related programs can be launched via the
.B Tools
menu
.
.Topic
The standard
.I Bibtex
entry types can be inserted in the
.B ".bib"
file with the
.B Bibliography
menu
.
.Topic
A
.I "structure view"
of the document for easier navigation of a document (by clicking on an
item in the
.I Structure
frame, you can jump directly to the corresponding part of your
document
.
.Topic
Extensive LaTeX documentation
.
.Topic
In the "Messages / Log File" frame, you can see information about
processes and the logfile after a LaTeX compilation
.
.Topic
The "Next Latex Error" and "Previous Latex Error" commands let you
reach the LaTeX errors detected in the log file
.
.Topic
By clicking on the number of a line in the log file, the cursor jumps
to the corresponding line in the editor
.
.Topic
An integrated LaTeX to html conversion tool (for unix and macosx
systems)
.
.
.SH Web Page
http://www.xm1math.net/texmaker/
.
.SH AUTHOR
Pascal Brachet <pbrachet@xm1math.net>
.
.\" EOF
